### ISSUE TITLE
Unable to order data

### ISSUE THREAD

**Issue by wblumberg** [jjhelmus/arm_archive#1]
Hi,

I've recently been playing with this program…it's really great and has significantly improved my ability to look up which files are available on the ARM archive.  Unfortunately, I'm encountering some difficulty with ordering data.  Am I using this correctly? (I've included some output from my debugging).

Thanks,

Greg

seabiscuit:arm_archive greg.blumberg$ apu order wblumberg -d sgpmplC1.a1 19990501 19990530
args.dates: ['sgpmplC1.a1', '19990501', '19990530']
args.file: None
[u'sgpmplC1.a1.19990501.000011.cdf' u'sgpmplC1.a1.19990502.000006.cdf'
 u'sgpmplC1.a1.19990503.000000.cdf' u'sgpmplC1.a1.19990504.000024.cdf'
 u'sgpmplC1.a1.19990505.000028.cdf' u'sgpmplC1.a1.19990506.200005.cdf'
 u'sgpmplC1.a1.19990513.090805.cdf' u'sgpmplC1.a1.19990514.000029.cdf'
 u'sgpmplC1.a1.19990515.000026.cdf' u'sgpmplC1.a1.19990516.000015.cdf'
 u'sgpmplC1.a1.19990517.000011.cdf' u'sgpmplC1.a1.19990518.000003.cdf'
 u'sgpmplC1.a1.19990519.000002.cdf' u'sgpmplC1.a1.19990520.000021.cdf'
 u'sgpmplC1.a1.19990521.000002.cdf' u'sgpmplC1.a1.19990522.000019.cdf'
 u'sgpmplC1.a1.19990523.000007.cdf' u'sgpmplC1.a1.19990524.000006.cdf'
 u'sgpmplC1.a1.19990525.000025.cdf' u'sgpmplC1.a1.19990526.000013.cdf'
 u'sgpmplC1.a1.19990527.000008.cdf' u'sgpmplC1.a1.19990528.000020.cdf'
 u'sgpmplC1.a1.19990529.000007.cdf'] wblumberg
response: None
Traceback (most recent call last):
  File "/Users/greg.blumberg/arm_archive/arm_archive.py", line 456, in <module>
    main()
  File "/Users/greg.blumberg/arm_archive/arm_archive.py", line 406, in main
    status, flag = order_files(args.user, files)
  File "/Users/greg.blumberg/arm_archive/arm_archive.py", line 139, in order_files
    match = pattern.search(response)
TypeError: expected string or buffer

**Comment by jjhelmus** [comment]
@wblumberg Glad to head you are finding the utility helpful.  What version of Python and suds do you have installed?   When I run the same command with my ARM Archive username I do not get an error and the file are ordered.  Looking at the intermediates in the script the elements of the files variable are not unicode as your debugging seems in indicate but rather suds.sax.text.Text objects.  This would suggest to me that something is changing the element type in the `list_files` function, perhaps a different version of Python or the suds library.

The output from the following two command should provide sufficient details:

``` shell
python -c "import sys; print(sys.version)"
python -c "import suds; print(suds.__version__)"
```

I get the following on my desktop:

```
$ python -c "import sys; print(sys.version)"
2.7.10 |Continuum Analytics, Inc.| (default, May 28 2015, 17:02:03) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]

$ python -c "import suds; print(suds.__version__)"
0.4
```

**Comment by jjhelmus** [comment]
It is also possible that I have as a ARM developer I have special permission at the Archive to order data from the web service that other users may not have.  I'll inquire about this at the developers meeting in a few weeks.

**Comment by wblumberg** [comment]
Hi @jjhelmus ...It looks like our output is similar, except for the OS.

```
seabiscuit:~ greg.blumberg$ python -c "import sys; print(sys.version)"
2.7.10 |Anaconda 2.1.0 (x86_64)| (default, May 28 2015, 17:04:42) 
[GCC 4.2.1 (Apple Inc. build 5577)]

seabiscuit:~ greg.blumberg$ python -c "import suds; print(suds.__version__)"
0.4
```

I also checked the type of all the variables (the response one).  You're correct.  They aren't returning as a suds.sax.text.Text object.

**Comment by jjhelmus** [comment]
Do you recall how and from where you installed suds?  I know there are a few versions out there and they may behave differently and report the same version.  Just to verify what is the following print out?

``` Python
import arm_archive
files = arm_archive.list_files('sgpmplC1.a1', '19990501', '199990530')
print type(files[0])
```

**Comment by wblumberg** [comment]
This is what I get:

```
>>> import arm_archive
>>> files = arm_archive.list_files('sgpmplC1.a1', '19990501', '199990530')
>>> print type(files[0])
<class 'suds.sax.text.Text'>
```

**Comment by jjhelmus** [comment]
No output from the print command?

**Comment by wblumberg** [comment]
Oh no.  The output from the print command was the "<class 'suds.sax.text.Text'>".

**Comment by jjhelmus** [comment]
Wait nevermind, GitHub's markdown rendering hid it

**Comment by wblumberg** [comment]
Oh!  I think I see the issue.  I made some modifications with the code in order to sort the listing of the files that I could order.  I used Numpy to do that, and it seems that importing it as np did something (I don't know what), but when I removed all numpy-related things in the code, the ordering works.

**Comment by jjhelmus** [comment]
Right, the files used to be ordered when returned from the archive, I see now they are not which is unfortunate.  I'll see if I can add a sort option.

**Comment by jjhelmus** [comment]
commit 54c486a will list the files and datastreams sorted by name.

**Comment by wblumberg** [comment]
Cool!  Thank you very much @jjhelmus .

**Comment by jjhelmus** [comment]
No problem, the output was bugging me too.  Does this solve the issue you were having (ie can I close this issue?)

**Comment by wblumberg** [comment]
Yep!  It did.  Although, it might be helpful for somewhere in the README to list some sample command line inputs.  I had trouble with getting the ordering of some of the arguments correctly, which is probably due to my lack of experience understanding what the help output is telling me.

**Comment by jjhelmus** [comment]
The help message are argparse standard but they can be a bit cryptic to understand.  I'll add some examples to the README file.  I'll also see about making this a more "real" Python package which is available on PyPI and can be installed with pip.

**Comment by wblumberg** [comment]
That would be great...I can see a lot of people in ARM using this (especially my advisor Dave Turner).

**Comment by jjhelmus** [comment]
Command line examples were added to the README.rst file and the package was added to PyPI which allows for it to be installed using pip.
