### ISSUE TITLE
ordering/listing files sometimes works

### ISSUE THREAD

**Issue by wblumberg** [jjhelmus/arm_archive#2]
I've been using this repository religiously, and it really simplifies large data orders.  I encountered some odd behaviors that I'm wondering if it may be related to me hitting the server so many times with this script.  Any ideas what this message might mean @jjhelmus ?  I was able to list files from the server a couple of times, but then the program started throwing this error.  My Google search doesn't give me a whole lot of insight.  I should add that I'm using the most recent version and Python 2.7

![screen shot 2016-02-01 at 1 43 01 pm](https://cloud.githubusercontent.com/assets/7607087/12727190/c5092e64-c8e9-11e5-8e46-f2454ab3953b.png)

**Comment by jjhelmus** [comment]
This is an error message from the SOAP server, which the SOAP client used in arm_archive is passing along, so something is broken on the server side.  Not much the client can do about this.

I cannot get any valid reply from the SOAP server at the moment so there might be an issue at the moment.

**Comment by wblumberg** [comment]
Oh well.  I'll just have to wait.  Thanks for the clarification!

**Comment by jjhelmus** [comment]
I checked on this again today I wasn't able to reproduce the problem.  Are you still seeing it?

**Comment by wblumberg** [comment]
Sorry to get back to you this late!  I was able to order stuff a few days ago this way and it worked out.  Thanks again!  I guess the server just doesn't work sometimes...

**Comment by jjhelmus** [comment]
No worries, going to close this issue for the time being.  Feel free to re-open is this issue returns.
